const products = [
  {
    id: 0,
    name: "iPhone 14",
    description: "El iPhone 14 Pro Max lleva la tecnología al siguiente nivel con su pantalla ProMotion, cámara de 48MP y un rendimiento increíble gracias al chip A16 Bionic.",
    price: 1099,
    stock: Math.floor(Math.random() * 100) + 1,
    image: "https://picsum.photos/200/300",
    categoryId: 0,
  },
  {
    id: 1,
    name: "MacBook Pro",
    description: "El MacBook Pro M2 Max ofrece un rendimiento sin precedentes para profesionales creativos, con gráficos avanzados y una batería de larga duración.",
    price: 2499,
    stock: Math.floor(Math.random() * 100) + 1,
    image: "https://picsum.photos/200/300",
    categoryId: 1,
  },
  {
    id: 2,
    name: "Apple Watch",
    description: "El Apple Watch Ultra está diseñado para aventuras extremas, con una durabilidad mejorada, mayor autonomía y capacidades avanzadas de salud y fitness.",
    price: 799,
    stock: Math.floor(Math.random() * 100) + 1,
    image: "https://picsum.photos/200/300",
    categoryId: 2,
  },
  {
    id: 3,
    name: "iPad Air",
    description: "El iPad Air 2023 combina la potencia del chip M1 con un diseño ligero y una pantalla Liquid Retina, ideal para cualquier tarea creativa.",
    price: 699,
    stock: Math.floor(Math.random() * 100) + 1,
    image: "https://picsum.photos/200/300",
    categoryId: 3,
  },
  {
    id: 4,
    name: "AirPods",
    description: "Los AirPods Max ofrecen un sonido de alta fidelidad con una cancelación de ruido líder en la industria y un diseño premium.",
    price: 549,
    stock: Math.floor(Math.random() * 100) + 1,
    image: "https://picsum.photos/200/300",
    categoryId: 4,
  },
  {
    id: 5,
    name: "Apple TV",
    description: "El Apple TV 4K 2023 mejora la experiencia de entretenimiento con soporte para Dolby Atmos, un rendimiento más rápido y un diseño compacto.",
    price: 199,
    stock: Math.floor(Math.random() * 100) + 1,
    image: "https://picsum.photos/200/300",
    categoryId: 5,
  },
  {
    id: 6,
    name: "Apple Home",
    description: "El HomePod Mini ofrece un sonido impresionante en un diseño compacto, con integración perfecta con tu ecosistema Apple y capacidades inteligentes.",
    price: 99,
    stock: Math.floor(Math.random() * 100) + 1,
    image: "https://picsum.photos/200/300",
    categoryId: 6,
  },
  {
    id: 7,
    name: "Apple Studio",
    description: "El Apple Studio Display es una pantalla 5K de 27 pulgadas que ofrece una calidad de imagen excepcional y un diseño elegante para cualquier espacio de trabajo.",
    price: 1599,
    stock: Math.floor(Math.random() * 100) + 1,
    image: "https://picsum.photos/200/300",
    categoryId: 7,
  },
];

export default products;
